default['ruby']['user'] = "vagrant"
default['ruby']['group'] = "vagrant"
default['ruby']['ruby_version'] = "2.3.1"
default['ruby']['rbenv_url'] = "git://github.com/sstephenson/rbenv.git"
default['ruby']['ruby-build_url'] = "git://github.com/sstephenson/ruby-build.git"
